### ISSUE TITLE
Please review this project

### ISSUE THREAD

**Issue by klavspc** [Septima/s3-demomodules#2]

**Comment by klavspc** [comment]
@bjornharrtell 
Thanks for the feedback. Martin has already factored adp into a package and I'll soon move datafordeler and cognito into separate packages.

A big question: How do we streamline development of these packages? I.e. make a smooth process of updating package code and seeing the changes in one's local s3? (I know how to debug because I know where to look in node_modules, but that may not be convenient for all)

If you recommend yarn link could you then please write a little section about that in the top readme? I could surely use that info when refactoring the mentioned modules

**Comment by bjornharrtell** [comment]
Yes I think yarn link is definitely the way. I've added a short section about it https://github.com/Septima/s3-demomodules/blob/master/README.md#development (https://github.com/Septima/septima-search-server/blob/master/README.md#development is more specific).

**Comment by klavspc** [comment]
> I've added a short section about it

Great - thanks

> A big question: How do we streamline development of these packages?

Another idea, which might work better for me; softlink a directory _mypackage_ under src/_packages_ (which is .gitignored) to the root of your package source. S3 will load from src/_packages_ if a package in import.yml can't be loaded from node_modules. In that way you may edit code in-place.

I see no problem in being able to develop in either of these ways.

**Comment by bjornharrtell** [comment]
I have no objections. 🙂
